# -*- coding: utf-8 -*-
"""CH8_StringsLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0YhpPFJHuuyI-38iu1VlBtIzmJ9aNID
"""

string = input("Enter a sentence:")
j = 0
for i in string:
  if i == 't' or i == 'T':
    j = j + 1
print(f"The letter T appears {j} times.")

Date = input("Enter a date (mm/dd/yyyy):")
Month = Date[:2]
Day = Date[3:5]
Year = Date[6:]
print(f"Month: {Month}\nDay: {Day}\nYear: {Year}")

firstname = input("Enter your first name:")
lastname = input("Enter your last name:")
studentID = input("Enter your student ID:")
threefn = firstname[:3]
threeln = lastname[:3]
threestuID = studentID[-3:]
print(f"Your system login name is: {threefn}{threeln}{threestuID}")

correct_length = False
has_uppercase = False
has_lowercase = False
has_digit = False
password = input("Please enter a password:")
if len(password) >= 7:
  for i in password:
    if i.isupper() == True:
      has_uppercase = True
    if i.islower() == True:
      has_lowercase = True
    if i.isdigit() == True:
      has_digit = True
  if has_digit == True and has_lowercase == True and has_uppercase == True:
    print('True')
  else:
    print('False')
else:
  print('False')